blank_issues_enabled: false
contact_links:
  - name: aster Discord discussion
    url: https://discord.gg/aster-oss
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/block/aster/security/policy
    about: Please report security vulnerabilities here.
